export const emptyValues = {
  "version": "1.6.1",
  "output":"",
  "resourcesDirectory":"",
  "threads":1,
  "experiments": [
    {
      "Files":"",
      "Sample":"",
      "Data type":"",
      "Condition":"",
      "Name":""
    }],
  "minimumReadLength":0,
  "minimumReadAverageQuality":0,
  "doAssembly":true,
  "maxMemory":1,
  "assembler":"",
  "errorModel":"",
  "markerset":"",
  "doIterativeBinning":true,
  "upimapiDatabase":"",
  "upimapiMaxTargetSeqs":1,
  "upimapiTaxids": "",
  "upimapiColumns":[],
  "upimapiDatabases":[],
  "downloadCddResources":false,
  "recognizerDatabases":[],
  "normalizationMethod":"",
  "minimumDifferentialExpression":1.0,
  "proteomicsWorkflow":"",
  "useCrap":false,
  "proteomicsContaminantesDatabase":"",
  "referenceProteomesTaxaLevel":"",
  "protease":"",
  "proteaseFile":"",
  "keggcharterTaxaLevel":"",
  "keggcharterNumberOfTaxa":1,
  "keggcharterMaps":[]
}
