export const assemblerOptions = ['metaspades', 'megahit']
export const errorModelOptions = ['complete', 'sanger_5', 'sanger_10', '454_10', '454_30', 'illumina_5', 'illumina_10']
export const markersetOptions = ['40', '107']
export const normalizationMethodOptions = ['TMM', 'RLE']
export const keggcharterTaxaLevelOptions = ['SPECIES', 'GENUS', 'FAMILY', 'ORDER', 'CLASS', 'PHYLUM', 'SUPERKINGDOM']
